services:
  postgresql:
    container_name: postgresql
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
          - ./contrib/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 1
      start_period: 20s
      timeout: 10s
